@startuml
Actor User

activate ":GUIDisplay"
User -> ":GUIDisplay" : Set cooler temperature

":GUIDisplay" -> ":ConfigurationMap" : coolerTemperature = Integer.parseInt(textfields.get("tFreezerTemp").getText())
activate ":ConfigurationMap"
":ConfigurationMap" -->> ":GUIDisplay": Successful?
deactivate ":ConfigurationMap"

":GUIDisplay" -> ":CoolerContext": setDesiredCoolerTemp(coolerTemperature)
activate ":CoolerContext"

":CoolerContext" -->> ":GUIDisplay" : Successful?
deactivate ":CoolerContext"
":GUIDisplay" -->> User : Successful?
deactivate ":GUIDisplay"
@enduml